AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:

  TestPythonFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./functions/test_python
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
